--- 
cache: 
  directories: 
    - ~/.npm
deploy: 
  commit_message: "Deploy Release"
  edge: true
  keep-history: true
  local-dir: dist/
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  true: 
    branch: main
git: "depth:3"
language: node_js
node_js: "-\"12\""
script: 
  - "yarn build"